language: go
sudo: false
go:
- 1.9

addons:
  apt:
    packages: rpm
install:
- gem install fpm
script:
- make prepare
- make build
- make rpm
before_deploy:
- export PACKAGE_NAME=$(ls build/oauth2-proxy-*.x86_64.rpm | tail -n1)
deploy:
- provider: script
  script: "curl -sS --fail -F \"uploadfile=@${PACKAGE_NAME}\" -H 'token: ${UPLOAD_TOKEN}' \"${UPLOAD_URL}\""
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_GO_VERSION = 1.8"
- provider: script
  script: "curl -sS --fail -F \"uploadfile=@${PACKAGE_NAME}\" -H 'token: ${UPLOAD_TOKEN}' \"${UPLOAD_URL}\""
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_GO_VERSION = 1.8"
